### ISSUE TITLE
Applying Coupon Code - throws error

### ISSUE THREAD

**Issue by RAGHURAMK0542** [troublediehard/magento-react-native#133] opened 2020-07-04 16:33 UTC
**Describe the bug**
I am trying to apply coupon code say for instance VIH9D5OWT3V28X - once i apply this code, getting the following error 
The "false" value's type is invalid. The 'Int' type was expected. Verify and try again

Then i tried with integer code 1000020. still getting the same error.

**Expected behavior**
Coupon applied with discount

**Current Behavior**
Throwing error

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.
1. Add Item to cart
2. Go to the cart and complete the 3 steps and navigate to summary section
3. Apply the code

4. The "false" value's type is invalid. The 'Int' type was expected. Verify and try again

**Screenshots**
<img width="376" alt="Screenshot 2020-07-04 at 10 02 14 PM" src="https://user-images.githubusercontent.com/64572499/86516880-0806be00-be42-11ea-964c-7e2e966e61df.png">

**Smartphone (please complete the following information):**
 - Magento Version: 2.1.0
 - Device: iPhone 6sPlus
 - OS: iOS 13.5.1

**Comment by troublediehard** [comment] 2020-07-04 17:58
@RAGHURAMK0542 I can't reproduce it on my end. 
For `VIH9D5OWT3V28X` coupon code - I'm getting error - no such coupon code. 
<img width="368" alt="Screenshot 2020-07-04 at 20 55 23" src="https://user-images.githubusercontent.com/6594232/86518264-fc62c980-be38-11ea-8174-eede95968b71.png">

`1000020` code works fine
<img width="367" alt="Screenshot 2020-07-04 at 20 55 53" src="https://user-images.githubusercontent.com/6594232/86518268-0a184f00-be39-11ea-96ef-043343511806.png">

**Comment by RAGHURAMK0542** [comment] 2020-07-04 18:14
This is the log i receive
<img width="1132" alt="Screenshot 2020-07-04 at 11 43 36 PM" src="https://user-images.githubusercontent.com/64572499/86518605-473c0b80-be50-11ea-8209-5599eab5b885.png">

**Comment by troublediehard** [comment] 2020-07-04 18:22
@RAGHURAMK0542 cart ID in your request is `false`, there is should be correct cart Id value instead.      

<img width="1132" alt="86518605-473c0b80-be50-11ea-8209-5599eab5b885" src="https://user-images.githubusercontent.com/6594232/86518733-4d27f180-be3c-11ea-9533-a34642d37288.png">

**Comment by RAGHURAMK0542** [comment] 2020-07-04 18:41
Yes, no matter what it's always false

**Comment by troublediehard** [comment] 2020-07-04 18:45
This issue isn't related to the coupon code, so I close it. 
Please create a new issue and provide steps to reproduce where cart id becomes false.

**Closed by troublediehard** 2020-07-04 18:45 UTC
Labels: bug, require feedback
